# Header
menu:
  首页: /
  前端: /categories/front-end
  后端: /categories/back-end
  标签: /tags
  归档: /archives
  订阅: /atom.xml
  关于: /about

# Content
excerpt_link: 阅读更多
content_max_width: 800px

# Sidebar
author:
  name: gitzxon 
  work: android developer
  location: Beijing, China
  avatar_url: /images/avatar.jpg

# Links:
links:
  - svg: ./source/svg/_github.svg
    url: 
  - svg: ./source/svg/_more.svg
    url: 
  - svg: ./source/svg/_twitter.svg
    url: 


# github comment 
git_commit:
  enable: true
  client_id: 
  client_secret: 
  repo: gitzxon.github.io
  owner: gitzxon
  admin:
    - gitzxon
  per_page: 10


# 百度统计
baidu:
  id: 

# Miscellaneous
rss: /atom.xml
favicon: /images/favicon.ico